# configs/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= # base64 of 'password'
  MYSQL_USER: dXNlcm5hbWU= # base64 of 'username'
  MYSQL_PASSWORD: cGFzc3dvcmQ= # base64 of 'password'
